# Generated by Django 5.0.1 on 2024-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('Not read', 'NR'), ('Read', 'R'), ('Pending', 'P')], default='Not read', max_length=16)),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('genre', models.CharField(default='Жанр', max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('statuses', models.ManyToManyField(blank=True, null=True, to='book.bookhistory')),
            ],
        ),
    ]
