# Generated by Django 5.0.1 on 2024-02-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                ("author", models.CharField(blank=True, max_length=128, null=True)),
                ("genre", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
